import sys
import time
import torch
import traceback
sys.path.insert(0, ".")
from scripts.e2e_benchmark import load_eagle_model, _llama3_input_ids

def run_debug():
    from transformers import AutoModelForCausalLM, AutoTokenizer
    print("\n==================================")
    print("Loading clean standalone AutoModelForCausalLM for isolation test in bfloat16. No EAGLE code is imported here.")
    print("==================================\n")
    try:
        model_id = "meta-llama/Llama-3.1-8B-Instruct"
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        # Load clean base model without EAGLE
        gen_model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16,
            device_map="auto",
            low_cpu_mem_usage=True,
        )
        gen_model.eval()
    except Exception as e:
        print("Failed to load clean model.")
        traceback.print_exc()
        return

    msg = "Say something intelligent."
    input_ids = _llama3_input_ids(tokenizer, msg, "cuda:0")

    print(f"\nPrompt: {msg}")
    print(f"Tokenized prompt: {input_ids}")

    print("\n--- Testing Base Model native generate (Standard Transformers) ---")
    try:
        base_out = gen_model.generate(
            input_ids,
            max_new_tokens=64,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )
        base_output_text = tokenizer.decode(base_out[0, input_ids.shape[1]:])
        print(f"Output generated by STANDARD base model: {base_output_text!r}")
        print("\nCONCLUSION:")
        print("If the above output IS NOT ' POLL POLL' (i.e. it says something normal), then we have irrefutable proof that EAGLE's customized `KVLlamaForCausalLM` architecture breaks LLaMA-3.1!")
        print("If the above output IS STILL ' POLL POLL', then LLaMA-3.1 is broken purely natively on Kaggle T4 GPUs (due to dtype or bitsandbytes absence).")
    except Exception as e:
        print("Base model generation failed:")
        traceback.print_exc()

if __name__ == "__main__":
    run_debug()
