import sys
import time
import torch
import traceback
sys.path.insert(0, ".")
from scripts.e2e_benchmark import load_eagle_model, _llama3_input_ids

def run_debug():
    print("Loading model...")
    try:
        model = load_eagle_model("meta-llama/Llama-3.1-8B-Instruct", "yuhuili/EAGLE3-LLaMA3.1-Instruct-8B", True, 60, 5, 10)
    except Exception as e:
        print("Failed to load model. Ensure you have Hugging Face access to Llama-3.1-8B-Instruct and are logged in via `huggingface-cli login`")
        traceback.print_exc()
        return

    msg = "Say something intelligent."
    input_ids = _llama3_input_ids(model.tokenizer, msg, "cuda:0")

    print(f"\nPrompt: {msg}")
    print(f"Tokenized prompt: {input_ids}")

    print("\n--- Testing EAGLE native eagenerate ---")
    try:
        out = model.eagenerate(input_ids, temperature=0.0, max_new_tokens=64)
        if isinstance(out, tuple):
            out_ids = out[0]
        else:
            out_ids = out
        output_text = model.tokenizer.decode(out_ids[0, input_ids.shape[1]:])
        print(f"Output generated by native eagenerate: {output_text!r}")
        print("If the above output IS gibberish, then EAGLE itself or the draft model compatibility is broken.")
        print("If the above output IS NOT gibberish, then our custom generation loop in e2e_benchmark.py is broken.")
    except Exception as e:
        print("Native generation failed:")
        traceback.print_exc()

if __name__ == "__main__":
    run_debug()
